Repository azerpas/prescurity-dashboard, pull requests merged in 2021-06, with the labels that each got.

#2 Changements du truc... test
  src/pages/index.tsx
Labels: enhancement, help wanted

#5 ajout trois BigBlock (Title+Text+Button) HomePage
  src/pages/index.tsx
  yarn.lock
Labels: done

#4 Initialisation de la page Login
  .gitignore
  package-lock.json
  package.json
  src/components/form/index.tsx
  src/components/header/index.tsx
  src/components/logo/index.tsx
  src/pages/doctorDashboard.tsx
  src/pages/login.tsx
  src/utils/admin.ts
  src/utils/client.ts
  yarn.lock
Labels: work in progress

#10 Persistence des données du User connecté
  src/components/header/index.tsx
  src/context/user.tsx
  src/entity/user.ts
  src/pages/_app.tsx
  src/pages/doctorDashboard.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/utils/client.ts
Labels: done

#11 Init Ethereum methods
  package.json
  src/utils/web3/index.ts
  window.d.ts
  yarn.lock
Labels: work in progress

#9 Dashboard/medpharma
  src/components/PostDoc/PostPrescription.tsx
  src/components/utils.js
  src/pages/doctor/index.tsx
  src/pages/pharmacist/index.tsx
Labels: work in progress

#14 Types definitions for the smart contract
  src/pages/dashboard.tsx
  src/types/user.ts
  src/utils/web3/index.ts
Labels: done

#17 Owner dashboard init
  src/components/owner/index.tsx
  src/contracts/Prescurity.json
  src/pages/dashboard.tsx
Labels: done

#13 Initialisation page sign up
  next-env.d.ts
  package-lock.json
  package.json
  src/components/form/index.tsx
  src/components/header/index.tsx
  src/entity/Doctor.ts
  src/entity/Patient.ts
  src/entity/Pharmacy.ts
  src/entity/User.ts
  src/pages/_app.tsx
  src/pages/api/user.ts
  src/pages/doctorDashboard.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/signOut.ts
  src/pages/signUp.tsx
  yarn.lock
Labels: work in progress

#21 Prescription cards for UI display
  src/components/card/prescription/index.tsx
  src/contracts/Migrations.json
  src/contracts/Prescurity.json
  src/entity/Prescription.ts
Labels: done
